-- vim.g.mkdp_open_to_the_world = 1
-- vim.g.mkdp_port = 8083
-- vim.g.mkdp_open_ip = '127.0.0.1'
--
-- vim.g.mkdp_browserfunc = function(url)
--     print('TTT222')
--     vim.cmd('wslview' .. url)
-- end
--
