#!/bin/zsh
# System confs
# -- ZSH/term configs
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git z)
source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color

# -- XDG config folder
export XDG_CONFIG_HOME="$HOME/.config"

# -- .local folder
LOCAL_FOLDER="$HOME/.local"

SYSTEM_PATHS="$LOCAL_FOLDER:$LOCAL_FOLDER/bin"
# ----------------------------------

# Languages
# -- Python
export PYENV_ROOT="$HOME/.pyenv"
PYTHON_PATHS="$PYENV_ROOT/bin"

# -- Dart
export DART_PATH="$HOME/.pub-cache/bin"

# -- Java
export JAVA_HOME="/usr/lib/jvm/java-25-openjdk"

# -- Go lang
# export GO_LANG_HOME="$HOME/Apps/go/bin"
export GO_BIN_PATH="/usr/local/go/bin"
export GOBIN="$HOME/App/go/bin"
export GOPATH="$HOME/Personal/.gopath"
GO_LANG_PATHS="$GO_BIN_PATH:$HOME/App/go/bin"

# -- Zig
export ZIG_PATH="$HOME/App/Zig"
export ZLS_PATH="$HOME/Repos/zls/zig-out/bin"

# -- NPM
NPM_PACKAGES="$HOME/.npm-packages"
NPM_PATHS="$NPM_PACKAGES/bin"

# -- NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# -- QMK
export QMK_HOME="$HOME/Personal/keyboards/qmk_firmware"

LANGUAGES_PATHS="$GO_LANG_PATHS:$NPM_PATHS:$PYTHON_PATHS:$ZLS_PATH:"
# ----------------------------------

# Apps
# -- Node
export NODE_OPTIONS="--max_old_space_size=8192"

APPS_PATHS=""
# ----------------------------------

# -- custom scripts
export PERSONAL_FOLDER="$HOME/Personal"
export SCRIPTS_FOLDER="$PERSONAL_FOLDER/scripts"
PERSONAL_PATHS="$SCRIPTS_FOLDER/scripts"

CUSTOM_PATHS="$PERSONAL_PATHS"
bindkey -s ^f "tmux-sessionizer\n"

# ----------------------------------

# ----------------------------------
export PATH="$SYSTEM_PATHS:$LANGUAGES_PATHS:$CUSTOM_PATHS:$PATH"
# ----------------------------------
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
# ----------------------------------

# Init custom confs
source $PERSONAL_FOLDER/scripts/scripts/init.sh

# Init Secrets
if [ -f "$HOME/.secrets" ]; then
    source $HOME/.secrets
fi
if [ -f "$HOME/Personal/secrets.sh" ]; then
    source $HOME/Personal/secrets.sh
fi
# Init  vars
if [ -f "$HOME/Personal/scripts/config/variables.sh" ]; then
    source $HOME/Personal/scripts/config/variables.sh
fi
# Plugins
#source /home/beto0607/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pyenv
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pnpm
export PNPM_HOME="/home/beto0607/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source <(kubectl completion zsh)  # set up autocomplete in zsh into the current shell
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/beto0607/App/google-cloud-sdk/path.zsh.inc' ]; then . '/home/beto0607/App/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/beto0607/App/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/beto0607/App/google-cloud-sdk/completion.zsh.inc'; fi
