#!/bin/zsh
# System confs
# -- ZSH/term configs
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git z)
source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color

# -- XDG config folder
export XDG_CONFIG_HOME="$HOME/.config"

# -- .local folder
LOCAL_FOLDER="$HOME/.local/"

SYSTEM_PATHS="$LOCAL_FOLDER:$LOCAL_FOLDER/bin"
# ----------------------------------

# Languages
# -- Python
export PYENV_ROOT="$HOME/.pyenv"
PYTHON_PATHS="$PYENV_ROOT/bin"

# -- Android/Flutter/Java
export ANDROID_SDK_ROOT="$HOME/App/Android/Sdk"
export ANDROID_HOME="$HOME/App/Android/Sdk"
export ANDROID_HOME="$HOME/App/Android/Sdk"
export ANDROID_AVD_HOME="$HOME/.config/.android/avd/"
export ANDROID_STUDIO="$HOME/App/Android/android-studio"
export FLUTTER_PATH="$HOME/App/flutter/bin"
export ANDROID_TOOLS="$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/latest/bin"
ANDROID_PATHS="$ANDROID_TOOLS:$FLUTTER_PATH"
# export JAVA_HOME="/usr/lib/jvm/default-java"
# export JAVA_HOME="/usr/lib/jvm/jdk-24-oracle-x64"
# export JAVA_HOME="/usr/lib/jvm/jdk-11.0.25-oracle-x64"

# -- Go lang
# export GO_LANG_HOME="$HOME/Apps/go/bin"
export GO_BIN_PATH="/usr/local/go/bin"
export GOBIN="$HOME/App/go/bin"
export GOPATH="$HOME/Personal/.gopath"
GO_LANG_PATHS="$HOME/App/go/bin"

# -- Rust
. "$HOME/.cargo/env"

# -- Zig
export ZIG_PATH="$HOME/App/Zig"

# -- Odin
export ODIN_PATH="$HOME/App/Odin"

# -- PHP
export LARAVEL_ROOT="$HOME/.config/composer/vendor/bin"

# -- NPM
NPM_PACKAGES="$HOME/.npm-packages"
NPM_PATHS="$NPM_PACKAGES/bin"

# -- NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# -- QMK
export QMK_HOME="$HOME/Personal/keyboards/qmk_firmware"

LANGUAGES_PATHS="$GO_BIN_PATH:$GOBIN:$GO_LANG_PATHS:$NPM_PATHS:$ANDROID_PATHS:$PYTHON_PATHS:$ZIG_PATH:$LARAVEL_ROOT:$ODIN_PATH"
# ----------------------------------

# Apps
# -- SpotifyD
export SPOTIFYD="$HOME/spotify/spotifyd/target/release"

# -- K9s
export K9S_PATH="$HOME/App/k9s/execs"

# -- Kitty
export KITTY_PATH="$HOME/.local/kitty.app/bin"

# -- NeoVim
export NVIM_PATH="$HOME/App/Nvim"

# -- Gitmux
export GITMUX_PATH="$HOME/App/gitmux"

# -- Node
export NODE_OPTIONS="--max_old_space_size=8192"

# -- Kubectl
export KUBECTL_PATH="$HOME/App/Kubectl"

# -- Postman
export POSTMAN_PATH="$HOME/App/Postman"

APPS_PATHS="$SPOTIFYD:$NVIM_PATH:$K9S_PATH:$KITTY_PATH:$GITMUX_PATH:$KUBECTL_PATH:$POSTMAN_PATH"
# ----------------------------------

# -- custom scripts
export PERSONAL_FOLDER="$HOME/Personal"
export SCRIPTS_FOLDER="$PERSONAL_FOLDER/scripts"
PERSONAL_PATHS="$SCRIPTS_FOLDER/scripts"

CUSTOM_PATHS="$PERSONAL_PATHS"
bindkey -s ^f "tmux-sessionizer\n"

# ----------------------------------

# ----------------------------------
export PATH="$SYSTEM_PATHS:$LANGUAGES_PATHS:$APPS_PATHS:$CUSTOM_PATHS:$PATH"
# ----------------------------------

# Init custom confs
source $PERSONAL_FOLDER/scripts/scripts/init.sh

# Init Secrets
if [ -f "$HOME/.secrets" ]; then
    source $HOME/.secrets
fi
if [ -f "$HOME/Personal/secrets.sh" ]; then
    source $HOME/Personal/secrets.sh
fi
# Plugins
#source /home/beto0607/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pyenv
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pnpm
export PNPM_HOME="/home/beto0607/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

source /home/beto0607/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Load Angular CLI autocompletion.
# source <(ng completion script)

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
