#!/bin/zsh
# System confs
# -- ZSH/term configs
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color

# -- XDG config folder
export XDG_CONFIG_HOME="$HOME/.config"

# -- .local folder
LOCAL_FOLDER="$HOME/.local/"

SYSTEM_PATHS="$LOCAL_FOLDER"
# ----------------------------------

# Languages
# -- Python
export PYENV_ROOT="$HOME/.pyenv"
PYTHON_PATHS="$PYENV_ROOT/bin"

# -- Android/Flutter/Java
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_STUDIO="$HOME/Android/android-studio"
export FLUTTER_PATH="$HOME/Flutter/bin"
export ANDROID_TOOLS="$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/bin"
export JAVA_HOME="/usr/lib/jvm/java-19-openjdk-amd64"

# -- Go lang
export GO_LANG_HOME="$HOME/Apps/go/bin"
export GOPATH="$HOME/Apps/go"
GO_LANG_PATHS="$GOPATH/bin:$GO_LANG_HOME"

# -- NPM
NPM_PACKAGES="$HOME/.npm-packages"
NPM_PATHS="$NPM_PACKAGES/bin"

# -- NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

LANGUAGES_PATHS="$GO_LANG_PATHS:$NPM_PATHS:$ANDROID_PATHS:$PYTHON_PATHS"
# ----------------------------------

# Apps
# -- SpotifyD
export SPOTIFYD="$HOME/spotify/spotifyd/target/release/"

APPS_PATHS="$SPOTIFYD"
# ----------------------------------

# -- custom scripts
export PERSONAL_FOLDER="$HOME/Personal"
export SCRIPTS_FOLDER="$PERSONAL_FOLDER/scripts"
PERSONAL_PATHS="$SCRIPTS_FOLDER/scripts"

CUSTOM_PATHS="$PERSONAL_PATHS"
# ----------------------------------

# ----------------------------------
export PATH="$SYSTEM_PATHS:$LANGUAGES_PATHS:$APPS_PATHS:$CUSTOM_PATHS:$PATH"
# ----------------------------------

# Init custom confs
source $PERSONAL_FOLDER/scripts/scripts/init.sh

# Plugins
source /home/beto0607/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pyenv
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
