#!/bin/zsh

if [[ -z $1 ]]; then
    echo "No ticket provided"
    exit 1
fi

local RFT_ID="91"
local RFD_ID="131"
local RFA_ID="71"
local PAUSED_ID="101"
local BLOCKED_ID="61"
local TO_DO_ID="81"
local IN_PROGRESS_ID="31"

local jiraTicket=$1
local targetTransition=$RFT_ID

local selectedOptionLowercase=$(echo "$2" | tr '[:upper:]' '[:lower:]')

case $selectedOptionLowercase in 
rft)
    targetTransition=$RFT_ID
    echo "Moving to 'Ready for Test'" ;; 
rfd)
    targetTransition=$RFD_ID
    echo "Moving to 'Ready for Deploy'" ;;
rfa)
    targetTransition=$RFA_ID
    echo "Moving to 'Ready for Acceptance'" ;;
wip)
    targetTransition=$IN_PROGRESS_ID
    echo "Moving to 'In Progress'" ;;
todo)
    targetTransition=$TO_DO_ID
    echo "Moving to 'To do'" ;;
paused)
    targetTransition=$PAUSED_ID
    echo "Moving to 'Paused'" ;;
blocked)
    targetTransition=$BLOCKED_ID
    echo "Moving to 'Blocked'" ;;
*)
    targetTransition=$RFT_ID
    echo "Default, moving to RfT" ;; 
esac


local jiraUrl="https://bannerflow.atlassian.net/rest/api/3/issue/$jiraTicket/transitions"

local data="{\"transition\":{\"id\":\"$targetTransition\"}}"

local responseCode=$(curl --request POST \
    $jiraUrl \
    --user $JIRA_USER:$JIRA_TOKEN \
    --header 'Content-Type: application/json' \
    --header 'Accept: application/json' \
    --write-out %{http_code} --silent \
    --data $data )

if [[ ${responseCode:0:1} == "2" ]]; then
    echo "oky doky"
else
    echo "Something went wrong D:"
fi
