#!/bin/zsh

local branchName="$1"
if [ -z "${branchName}" ];  then
    branchName=$(git branch -al --format='%(refname:lstrip=-1)' | grep -v -e 'HEAD\|main' | sort | uniq | fzf --bind 'ctrl-n:print-query')
fi

if [ -z "${branchName}" ];  then
    echo "No branch selected D:"
    exit 1
fi

local repoName="$(git remote get-url origin | sed -r 's/^.*\/(.*)\.git$/\1/i')"

local targetDir="../${repoName}-${branchName}"

if ! branchExists=$(git branch --list -a | grep -q "${branchName}")
then
    echo "New branch detected. Creating..."
    git worktree add --track -b ${branchName} ${targetDir}
else
    echo "Existing branch detected. Checking out..."
    git worktree add ${targetDir} --checkout ${branchName}
fi

echo "New worktree created"

echo "Changing directory to ${targetDir}"
cd "${targetDir}"

if [ -f "../${repoName}/pnpm-lock.yaml" ]
then
    echo "'pnpm-lock.yaml' detected, running pnpm install..."
    pnpm i > /dev/null 2> /dev/null
    echo "'pnpm i' done"
fi

if [ -f "../${repoName}/package-lock.json" ]
then
    echo "'package-lock.json' detected, running npm install..."
    npm i > /dev/null 2> /dev/null
    echo "'npm i' done"
fi

tmux-sessionizer "$(pwd)/${targetDir}"
