#!/bin/zsh

local branchName="$1"
if [ -z "${branchName}" ];  then
    echo "No branch name"
    exit 1
fi

local repoName="$(git remote get-url origin | sed -r 's/^.*\/(.*)\.git$/\1/i')"

local targetDir="../${repoName}-${branchName}"

if ! branchExists=$(git branch --list | grep -q "${branchName}")
then
    echo "New branch detected. Creating..."
    git worktree add --track -b ${branchName} ${targetDir}
else
    echo "Existing branch detected. Checking out..."
    git worktree add ${targetDir} --checkout ${branchName}
fi

echo "New worktree created"

if [ -d "./node_modules" ]
then
    echo "'node_modules' detected, copying..."
    # cp -r ./node_modules ${targetDir}/node_modules
    ln -s ../${repoName}/node_modules ${targetDir}/node_modules
    echo "'node_modules' copíed"
fi

echo "Changing directory to ${targetDir}"
cd "${targetDir}"


if [ -d "./node_modules" ]
then
    echo "Rebuild NPM"
    npm rebuild
fi

tmux-sessionizer "${targetDir}"
